services:
  db:
    image: mysql:8.0
    container_name: mysql_db_pessoas
    restart: always
    environment:
      MYSQL_DATABASE: db_pessoas
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
